name: popato_notes
description: "Create simple notes."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^4.4.0
  intl: ^0.18.1
  get_it: ^7.2.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  deepcopy: ^1.1.2
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icon.jpg
